require("dotenv").config();

module.exports = {
  token: process.env.TOKEN,
  clientId: process.env.CLIENT_ID,
  guildId: process.env.GUILD_ID,
  threadChannelId: process.env.THREAD_CHANNEL_ID,
  forumTagHC: process.env.FORUM_TAG_HC,
  forumTagCL: process.env.FORUM_TAG_CL,
  forumTagDDN: process.env.FORUM_TAG_DDN,
  forumTagDDNHC: process.env.FORUM_TAG_DDN_HC,
  forumTagSDNHC: process.env.FORUM_TAG_SDN_HC,
  forumTagSDNCore: process.env.FORUM_TAG_SDN_CORE,
  forumTagMarathonGDN: process.env.FORUM_TAG_MARATHON_GDN,
  forumTagMarathonDDN: process.env.FORUM_TAG_MARATHON_DDN,
  renderUrl: process.env.RENDER_URL,
  port: process.env.PORT || 3000,
  mongoUri: process.env.MONGODB_URI,
  mongoDbName: process.env.MONGODB_DB_NAME || "bot-raid",
  coLeaderRoleId: process.env.COLEADER_ROLE_ID,
  digestChannelId: process.env.DIGEST_CHANNEL_ID,
  top5ChannelId: process.env.TOP5_CHANNEL_ID,
  lzChannelId: process.env.LZ_CHANNEL_ID,
  bountyBoardChannelId: process.env.BOUNTY_BOARD_CHANNEL_ID,
  tim1RoleId: process.env.TIM1_ROLE_ID,
  tim2RoleId: process.env.TIM2_ROLE_ID,
};
