require("dotenv").config();

module.exports = {
  token: process.env.TOKEN,
  clientId: process.env.CLIENT_ID,
  guildId: process.env.GUILD_ID,
  threadChannelId: process.env.THREAD_CHANNEL_ID,
  forumTagHC: process.env.FORUM_TAG_HC,
  forumTagCL: process.env.FORUM_TAG_CL,
  forumTagSDNHC: process.env.FORUM_TAG_SDN_HC,
  forumTagDDN: process.env.FORUM_TAG_DDN,
  forumTagDDNHC: process.env.FORUM_TAG_DDN_HC,
  forumTagMarathonGDN: process.env.FORUM_TAG_MARATHON_GDN,
  forumTagMarathonDDN: process.env.FORUM_TAG_MARATHON_DDN,
  renderUrl: process.env.RENDER_URL,
  port: process.env.PORT || 3000,
  mongoUri: process.env.MONGODB_URI,
  mongoDbName: process.env.MONGODB_DB_NAME || "bot-raid",
  coLeaderRoleId: process.env.COLEADER_ROLE_ID,
  digestChannelId: process.env.DIGEST_CHANNEL_ID,
  top5ChannelId: process.env.TOP5_CHANNEL_ID,
  lzChannelId: process.env.LZ_CHANNEL_ID,
  publicRaidChannelId: process.env.PUBLIC_RAID_CHANNEL_ID,
  publicNestChannelId: process.env.PUBLIC_NEST_CHANNEL_ID,
  bountyBoardChannelId: process.env.BOUNTY_BOARD_CHANNEL_ID,
  bountyMeChannelId: process.env.BOUNTY_ME_CHANNEL_ID,
  rolePickChannelId: process.env.ROLE_PICK_CHANNEL_ID,
  kirimGajiChannelId: process.env.KIRIM_GAJI_CHANNEL_ID,
  gajiSayaChannelId: process.env.GAJI_SAYA_CHANNEL_ID,
  raidRoleId: process.env.RAID_ROLE_ID,
  nestRoleId: process.env.NEST_ROLE_ID,
  bountyAdminChannelId: process.env.BOUNTY_ADMIN_CHANNEL_ID,
  bountyHunterRoleId: process.env.BOUNTY_HUNTER_ROLE_ID,
  tim1RoleId: process.env.TIM1_ROLE_ID,
  tim2RoleId: process.env.TIM2_ROLE_ID,
};
